name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: No of Lines
      run: git ls-files | grep "\.java$" | wc -l
    - name: Adding to read me
      run: |
        git config --global user.email "myvinbarboza@gmail.com"
        git config --global user.name "MyvinB"
        touch git ls-files | grep "\.java$" | wc -l > REAR.txt
        git add .
        git commit -m "adding count"
        git push -u origin master
          
    
